### ISSUE TITLE
MangaInfo .getImageURL url incorrect

### ISSUE THREAD

**Issue by Doomsdayrs** [codingotaku/JEdenManga#1]
Returns https://cdn.mangaeden.com/mangasimg/http://www.mangaupdates.com/image/i218756.jpg instead of https://www.mangaupdates.com/image/i218756.jpg

**Comment by codingotaku** [comment]
Oh no.. that's embarrassing..
![embarrassed](http://gifimage.net/wp-content/uploads/2017/07/embarred-anime-gif-17.gif)
**I will fix it soon, Thank you for your contribution!**

**Comment by codingotaku** [comment]
Issue is fixed in the [Pre-release: v1.0.1](https://github.com/codingotaku/JEdenManga/releases/tag/v1.0.1). Hence closing the issue.

Thank you for your support ^_^!

![Happy anime girl](https://media.giphy.com/media/lsCf8zDfK0Pcc/giphy.gif)
